config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Routes for compatibility with old sites
  match 'details.php' => 'parts#showsfpartsid', via: :get
  match 'ArticleVariant.aspx' => 'parts#showsfpartsid', via: :get
  match 'ft-article/:id' => 'parts#showFtdb30TicketNumber', via: :get
  match 'search.php' => 'parts#index', via: :get
  match 'tickets' => 'parts#index', via: :get
  match 'binary/:id' => 'parts#attachmentFtdb30TicketNumber', via: :get
  match 'categories.php' => 'categories#showsfpartsid', via: :get
  match 'parts/partlistFtdb30TicketNumber/:id' => 'parts#partlistFtdb30TicketNumber', via: :get

  resources :parts do
    get :overlay
    get :partlist
    get :variants
    get :contained
    get :newpartgroup
    get "showhist/:idx", to: "parts#showhist"
    get "partlisthist/:idx", to: "parts#partlisthist"
    delete "restore/:idx", to: "parts#restore"
  end
  resources :categories

  resources :my_parts

  root to: 'parts#index'

  get "/about", to: "application#about"
  get "/token_refresh", to: "application#token_refresh"
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  title      :string
#  parent_id  :integer
#  sfpartsid  :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  remarks    :text
#
class Category < ApplicationRecord
	belongs_to :parent, :class_name => 'Category', inverse_of: :categories, optional: true
	has_many :categories, :class_name => 'Category', inverse_of: :parent, index_errors: :nested_attributes_order
	has_many :part_groups

	default_scope { order(title: :asc) }

	accepts_nested_attributes_for :categories, :allow_destroy => true

	validates :title, presence: true, uniqueness: { scope: :parent_id }

	def all_parents
		l = []
		category = self
		while category != nil do
			l.append(category)
			category = category.parent
		end
		return l.reverse
	end

	def full_title
		Rails.cache.fetch ["category_fulltitle", cache_key_with_version] do
			all_parents.map{|cat| cat.title}.join(" / ")
		end
	end

	def all_categories
		Rails.cache.fetch ["all_categories", cache_key_with_version] do
			cats = []

			cats << self
			categories.each do |cat|
				cats.concat(cat.all_categories())
			end

			return cats
		end
	end

	def url_show
		return {controller: "categories", action: "showsfpartsid", id: sfpartsid} if !sfpartsid.nil?
		return {controller: "categories", action: "show", id: id}
	end

	def destroy
		raise "Cannot delete category with subcategories" unless categories.count == 0
		raise "Cannot delete category with parts" unless part_groups.count == 0
		super
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :signed_in_editor?,  only: [:update]

	def show
		@category = Category.find(params[:id])
	end

	def showsfpartsid
		@category = Category.find_by_sfpartsid(params[:id])
		render :action => 'show'
	end

	def edit
		@category = Category.find(params[:id])
	end

	def update
		@category = Category.find(params[:id])

		if @category.update(category_params)
			flash[:success] = t('flash.update', name: @category.title)
			redirect_to @category
		else
			flash[:danger] = t('flash.error')
			render :edit, status: :unprocessable_entity
		end
	end

	private
		def category_params
			params.require(:category).permit(:remarks, categories_attributes: [:id, :title, :_destroy])
		end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category_fields.html.erb
<% errors = nil if !local_assigns[:errors] %>
<div class="category-field row">
	<div class="col-lg-8">
		<%= f.label :title, t("category.one"), class: "form-label" %><br>
		<%= f.text_field :title, class: "form-control" %>
		<% errors&.full_messages_for("categories[#{f.index}].title")&.each do |message| %>
			<div class="text-danger"><%= message %></div>
		<% end %>
	</div>

	<div class="col-lg-4 d-flex">
		<%= link_to_remove_association f, class: "btn btn-danger mt-auto " + (f.object.categories.size > 0 || f.object.part_groups.size > 0 ? "disabled" : "") do %>
			<i class="bi bi-trash"></i>
		<% end %>
	</div>
</div>

app/views/categories/edit.html.erb
<% provide(:title, t(:edit, title: @category.title)) %>
<div class="container-fluid">
	<h1>
		<%= t :edit, title: @category.title %>
	</h1>

	<%= form_with model: @category do |form| %>
		<div class="mb-12">
			<%= form.label :remarks, t("category.remarks"), class: "form-label" %><br>
			<%= form.text_area :remarks, class: "form-control", title: "Markdown supported" %><br>
			<% @category.errors.full_messages_for(:remarks).each do |message| %>
				<div class="text-danger"><%= message %></div>
			<% end %>
		</div>
		<div data-controller="nested-rondo" data-nested-rondo-field-class-value="category-field">
			<h2>
				<%= t("category.other") %>
			</h2>
			<div data-nested-rondo-target="fieldContain">
				<%= form.fields_for :categories do |cat_form| %>
					<%= render "category_fields", f: cat_form, errors: @category.errors %>
				<% end %>
			</div>
			<%= link_to_add_association t('add', name: t('category.one')), form, :categories %>
		</div>

		<div class="mt-3 me-3 position-fixed top-0 end-0">
			<%= form.submit t(:save), :class => "btn btn-primary" %>
			<%= link_to t(:cancel), category_path(@category), class: "btn btn-secondary" %>
		</div>
	<% end %>
</div>

app/views/categories/show.html.erb
<% provide(:title, @category.full_title) %>

<div class="container-fluid">
	<div class="row">
		<div class="col-lg-11 mb-2">
			<h1>
				<%= @category.title %>
			</h1>
		</div>
		<div class="col-lg-1">
			<div class="btn-group float-end" role="group">
				<% if edit_allowed? %>
					<%= link_to edit_category_path(@category), class: "btn btn-primary", title: t(:edit, title: @category.title) do %>
						<i class="bi bi-pencil"></i>
					<% end %>
					<%= link_to({controller: "parts", action: "newpartgroup", part_id: @category.id}, class: "btn btn-success", title: t(:new)) do %>
						<i class="bi bi-file-earmark-plus"></i>
					<% end %>
				<% end %>
			</div>
		</div>
	</div>
	<% if !@category.remarks.blank? %>
		<div class="row" id="category_app">
			<div class="col-lg-12">
				<span v-html="formatMarkdown('<%=@category.remarks.gsub("'", "\\'").gsub("\r", "\\r").gsub("\n", "\\n")%>')">
				</span>
			</div>
		</div>
	<% end %>
	<div class="row">
		<div class="col-lg-12 mb-2">
			<div class="accordion" id="accordionCategories">
				<% if @category.categories.size > 0 %>
					<div class="accordion-item">
						<h2 class="accordion-header" id="headingCategory">
							<button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseCategories" aria-expanded="true" aria-controls="collapseCategories">
								<%= t(:category, count: @category.categories.size) %>
							</button>
						</h2>
						<div id="collapseCategories" class="accordion-collapse collapse show" aria-labelledby="headingCategory">
							<div class="accordion-body">
								<div class="list-group list-group-horizontal flex-wrap">
									<% @category.categories.each do |category| %>
										<%= link_to category.title, category.url_show, class: "list-group-item catlink", data: {orighref: url_for(category.url_show)} %>
									<% end %>
								</div>
							</div>
						</div>
					</div>
				<% end %>
				<div class="accordion-item">
					<h2 class="accordion-header" id="headingParts">
						<button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseParts" aria-expanded="true" aria-controls="collapseParts">
							<%= t(:part, count: @category.part_groups.size) %>
						</button>
					</h2>
					<div id="collapseParts" class="accordion-collapse collapse show" aria-labelledby="headingParts">
						<div class="accordion-body">
							<%= render "parts/searchtableapp", category: @category %>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<%= javascript_include_tag 'categories_vue' %>