config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Routes for compatibility with old sites
  match 'details.php' => 'parts#showsfpartsid', via: :get
  match 'ArticleVariant.aspx' => 'parts#showsfpartsid', via: :get
  match 'ft-article/:id' => 'parts#showFtdb30TicketNumber', via: :get
  match 'search.php' => 'parts#index', via: :get
  match 'tickets' => 'parts#index', via: :get
  match 'binary/:id' => 'parts#attachmentFtdb30TicketNumber', via: :get
  match 'categories.php' => 'categories#showsfpartsid', via: :get
  match 'parts/partlistFtdb30TicketNumber/:id' => 'parts#partlistFtdb30TicketNumber', via: :get

  resources :parts do
    get :overlay
    get :partlist
    get :variants
    get :contained
    get :newpartgroup
    get "showhist/:idx", to: "parts#showhist"
    get "partlisthist/:idx", to: "parts#partlisthist"
    delete "restore/:idx", to: "parts#restore"
  end
  resources :categories

  resources :my_parts

  root to: 'parts#index'

  get "/about", to: "application#about"
  get "/token_refresh", to: "application#token_refresh"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
	<head>
		<title>
			<%= full_title(yield(:title)) %>
		</title>
		<meta name="viewport" content="width=device-width,initial-scale=1">
		<%= csrf_meta_tags %>
		<%= csp_meta_tag %>

		<%= stylesheet_link_tag 'application', media: 'all' %>
		<%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
	</head>

	<body data-user="<%= @user&.username %>">
		<% if !@user.nil? %>
			<datalist id="myCommentOptions">
				<% @user.my_parts.where.not(:comment => nil).select(:comment).distinct.each do |mypart| %>
					<option value="<%= mypart.comment %>">
				<% end %>
			</datalist>
		<% end %>
		<nav class="navbar navbar-expand-lg navbar-light bg-light" style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
			<div class="container-fluid">
				<%= link_to image_tag("/logo.png", alt: "ft db 4.0 logo"), root_path, class: "navbar-brand" %>
				<ul class="navbar-nav mb-2 mb-lg-0">
					<% if !@user.nil? %>
						<li class="nav-item">
							<%= link_to t('nav.myparts'), my_parts_path, class: "nav-link" + (params[:controller] == "my_parts" ? ' active' : '')  %>
						</li>
					<% end %>
				</ul>
				<div class="vr me-2"></div>
				<ol class="breadcrumb me-auto mb-2 mb-lg-0">
					<% category = @category %>
					<% categories = [] %>
					<% until category.nil? do %>
						<% categories.push category %>
						<% category = category.parent %>
					<% end %>
					<li class="breadcrumb-item">
						<%= link_to t('category.all'), root_path %>
					</li>
					<% categories.reverse.each do |category| %>
						<li class="breadcrumb-item">
							<%= link_to category.title, category.url_show %>
						</li>
					<% end %>
				</ol>
				<div class="vr me-2"></div>
				<% if @user %>
					<div class="navbar-brand">
						<small>
							<i class="bi bi-person-circle"></i>
							<%= @user.username %>
						</small>
					</div>
				<% else %>
					<a class="navbar-brand" href="/oauth2/sign_in" title="<%= t(:loginhelp) %>">
						<small>
							<i class="bi bi-person-circle"></i>
							<%= t(:login) %>
						</small>
					</a>
				<% end %>
				<div class="vr me-2"></div>
				<div class="flex-column">
					<% if params[:controller] != "parts" or params[:action] != "index" %>
						<%= link_to t(:back), root_path, class: "nav-link float-end me-2 align-items-start", :onclick => "if (history.length > 2) {history.back(); return false;}" %>
					<% end %>
					<%= link_to image_tag("/ftclogo.png", alt: "ftc logo"), "https://ftcommunity.de/", class: "nav-link align-items-end" %>
				</div>
			</nav>
		</div>
		<% flash.each do |type, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-#{type}") %>
		<% end %>
		<%= yield %>
		<div id="rowpopover" style="position: absolute;"></div>
		<%- if Rails.env.development? %>
			<%= console %>
			<%= debug(params) %>
		<%- end %>
	</body>
	<hr>
	<ul class="nav">
		<li class="nav-item">
			<a class="nav-link" href="https://ftcommunity.de/fans/verein/impressum/">
				<%= t("nav.legal_notice") %>
			</a>
		</li>
		<li class="nav-item">
			<%= link_to t("nav.about"), about_path, class: "nav-link" + (params[:controller] == "application" && params[:action] == "about" ? ' active' : '') %>
		</li>
		<li class="nav-item">
			<a class="nav-link" href="/api-docs">API</a>
		</li>
		<li class="nav-item">
			<a class="nav-link" href="https://gitlab.com/Humpelstilzchen/ftdb">Software</a>
		</li>
	</ul>

	<!--
	jwt: <%= request.headers["HTTP_AUTHORIZATION"] %>
	-->
</html>

app/views/layouts/overlay.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>